In [1]:
import pandas

In [2]:
# Cell 1: Import Libraries and Set Display Options
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)
pd.set_option('display.float_format', '{:,.2f}'.format)

print("=" * 70)
print("FORECAST vs ACTUALS - WMAPE & VARIANCE ANALYSIS")
print("=" * 70)

======================================================================
FORECAST vs ACTUALS - WMAPE & VARIANCE ANALYSIS
======================================================================

In [3]:
# data_path_prediction=r'D:\PivotX_advisors\Abhishek_csvs\forecast_nov2025_jan2026_L5_new.csv'
# data_path_prediction=r'D:\PivotX_advisors\level5\forecast_14months_level5_combined.csv'
# data_path_prediction=r"C:\Users\rohan\Downloads\forecasts_3months 3 (1).csv"
data_path_prediction= r"D:\PivotX_advisors\Abhishek_csvs\forecasts_3months_reconciled_to_direct_level2.csv"
df_forecast = pd.read_csv(data_path_prediction)

print(f"Dataset Shape: {df_forecast.shape[0]:,} rows × {df_forecast.shape[1]} columns")
# print(f"Date Range: {df_forecast['date'].min()} to {df_forecast['date'].max()}")
print(f"\nColumns: {df_forecast.columns.tolist()}")
print(f"\nData Types:\n{df_forecast.dtypes}")
# df_forecast.head()

Dataset Shape: 2,862 rows × 21 columns

Columns: ['opcos', 'entity_region', 'entity_country', 'entity_name', 'account_name', 'level2', 'level5', 'date', 'forecast_horizon', 'occur_prob', 'forecast_amount', 'forecast_amount_uncapped', 'cap_abs', 'zero_ratio_hist', 'hist_variance', 'method', 'bottom_parent_total', 'direct_level2_total', 'recon_factor', 'recon_factor_raw', 'forecast_amount_before_recon']

Data Types:
opcos                            object
entity_region                    object
entity_country                   object
entity_name                      object
account_name                     object
level2                           object
level5                           object
date                             object
forecast_horizon                  int64
occur_prob                      float64
forecast_amount                 float64
forecast_amount_uncapped        float64
cap_abs                         float64
zero_ratio_hist                 float64
hist_variance                   float64
method                           object
bottom_parent_total             float64
direct_level2_total             float64
recon_factor                    float64
recon_factor_raw                float64
forecast_amount_before_recon    float64
dtype: object

In [4]:
df_forecast['date'] = pd.to_datetime(df_forecast['date'], errors='coerce')
df_forecast['month'] = df_forecast['date'].dt.to_period('M')

df_forecast_monthly = (
    df_forecast.groupby(
        ['month', 'opcos', 'entity_region','entity_country',
         'entity_name','account_name','level2','level5'],
        as_index=False
    ).agg({
        'forecast_amount': 'sum',
        'forecast_amount_uncapped': 'sum',
        # 'predicted_amount_raw': 'sum',   # or 'mean' depending on logic
        # 'occur_prob': 'mean'             # probability → usually mean
    })
)

print(df_forecast_monthly)

        month opcos entity_region  entity_country  \
0     2026-02   HDS          AMER          Canada
1     2026-02   HDS          AMER          Canada
2     2026-02   HDS          AMER          Canada
3     2026-02   HDS          AMER          Canada
4     2026-02   HDS          AMER          Canada
...       ...   ...           ...             ...
2857  2026-04    HV          EMEA  United Kingdom
2858  2026-04    HV          EMEA  United Kingdom
2859  2026-04    HV          EMEA  United Kingdom
2860  2026-04    HV          EMEA  United Kingdom
2861  2026-04    HV          EMEA  United Kingdom

                                     entity_name account_name  \
0     Hitachi Digital Services Canada Inc. 00190   4000011853
1     Hitachi Digital Services Canada Inc. 00190   4000011853
2     Hitachi Digital Services Canada Inc. 00190   4000011853
3     Hitachi Digital Services Canada Inc. 00190   4000011853
4     Hitachi Digital Services Canada Inc. 00190   4000011855
...                                          ...          ...
2857   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
2858   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
2859   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
2860   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
2861   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145

                level2                      level5  forecast_amount  \
0       Free Cash Flow           A/R - Collections       234,141.99
1       Free Cash Flow          AP - OPEX Payments       -96,183.30
2       Free Cash Flow            Payroll Payments      -120,661.33
3       Free Cash Flow  Related Parties - Receipts             0.00
4       Free Cash Flow           A/R - Collections     1,106,133.91
...                ...                         ...              ...
2857    Free Cash Flow      Miscellaneous Receipts     3,417,405.17
2858    Free Cash Flow  Related Parties - Receipts         8,169.81
2859  Interco Payments     Interco Payments - Loan    -4,568,406.64
2860  Interco Payments    Interco Payments - Trade             0.00
2861  Interco Receipts     Interco Receipts - Loan             0.00

      forecast_amount_uncapped
0                   709,521.19
1                  -291,464.54
2                  -365,640.39
3                         0.00
4                   368,711.30
...                        ...
2857              1,172,916.99
2858                  2,804.03
2859             -2,105,198.04
2860                      0.00
2861                      0.00

[2862 rows x 10 columns]

In [4]:
# import pandas as pd

# # Ensure date column is datetime
# df_forecast['date'] = pd.to_datetime(df_forecast['date'], errors='coerce')
# # Add level2 mapping
# # df_forecast['level2'] = df_forecast['level5'].map(level2_map)

# # Create year-month period column
# df_forecast['month'] = df_forecast['date'].dt.to_period('M')

# # Group by monthly level
# df_forecast_monthly = (
#     df_forecast.groupby(['month', 'opcos', 'entity_region','entity_country','entity_name','account_name','level2','level5'], as_index=False)
#     ['forecast_amount']
#     .sum()
# )

# print(df_forecast_monthly)

In [79]:
# df_forecast_monthly[:100]

In [5]:
# Cell 2: Load Data
data_path_1 = r'D:\PivotX_advisors\level5\bquxjob_eb6c43c_19d39d13f8f.csv'
df_actual_1 = pd.read_csv(data_path_1)

print(f"Dataset Shape: {df_actual_1.shape[0]:,} rows × {df_actual_1.shape[1]} columns")
# print(f"Date Range: {df_actual['date'].min()} to {df_actual['date'].max()}")
print(f"\nColumns: {df_actual_1.columns.tolist()}")
print(f"\nData Types:\n{df_actual_1.dtypes}")
# df_actual.head()

Dataset Shape: 4,631 rows × 45 columns

Columns: ['flow_category', 'bank_branch_id', 'source', 'instance', 'account', 'account_business_id', 'id', 'source_primary_key', 'source_file_name', 'account_identifier', 'transaction_currency', 'transaction_amount', 'value_datetime', 'booking_datetime', 'description', 'extended_details', 'canonical_update_timestamp', 'account_name', 'account_alternative_name', 'account_holder', 'account_holder_id', 'account_class', 'cash_pool_role', 'cash_pool_name', 'bank_name', 'account_currency', 'entity_country', 'entity_name', 'entity_alternative_name', 'entity_code', 'entity_currency', 'entity_region', 'entity_top_level', 'branch_name', 'level1', 'level2', 'level3', 'level4', 'level5', 'fx_rate', 'transaction_amount_usd', 'forecast_flag', 'opcos', 'period_month', 'date']

Data Types:
flow_category                  object
bank_branch_id                 object
source                         object
instance                       object
account                        object
account_business_id            object
id                             object
source_primary_key             object
source_file_name               object
account_identifier             object
transaction_currency           object
transaction_amount            float64
value_datetime                 object
booking_datetime               object
description                    object
extended_details               object
canonical_update_timestamp     object
account_name                   object
account_alternative_name       object
account_holder                 object
account_holder_id              object
account_class                  object
cash_pool_role                 object
cash_pool_name                 object
bank_name                      object
account_currency               object
entity_country                 object
entity_name                    object
entity_alternative_name        object
entity_code                   float64
entity_currency                object
entity_region                  object
entity_top_level               object
branch_name                    object
level1                         object
level2                         object
level3                         object
level4                         object
level5                         object
fx_rate                       float64
transaction_amount_usd        float64
forecast_flag                  object
opcos                          object
period_month                   object
date                          float64
dtype: object

In [6]:
columns_to_keep =['opcos','value_datetime','entity_region','entity_country','entity_name','account_name','level2','level5','transaction_amount_usd']
df_actual_1=df_actual_1[df_actual_1['source']=='OAT']
df_actual_1=df_actual_1[columns_to_keep]
df_actual_1.isnull().sum()

opcos                     7
value_datetime            0
entity_region             0
entity_country            0
entity_name               0
account_name              0
level2                    0
level5                    0
transaction_amount_usd    0
dtype: int64

In [7]:
df_actual_1=df_actual_1.dropna()
df_actual_1=df_actual_1.rename(columns={'transaction_amount_usd':'actual_amount','value_datetime':'date'})

In [8]:
import pandas as pd

# Ensure date column is datetime
df_actual_1['date'] = pd.to_datetime(df_actual_1['date'], errors='coerce')
# Add level2 mapping
# df_forecast['level2'] = df_forecast['level5'].map(level2_map)

# Create year-month period column
df_actual_1['month'] = df_actual_1['date'].dt.to_period('M')

# Group by monthly level
df_actual_monthly = (
    df_actual_1.groupby(['month', 'opcos', 'entity_region','entity_country','entity_name','account_name','level2','level5'], as_index=False)
    ['actual_amount']
    .sum()
)

print(df_actual_monthly)

        month opcos entity_region  entity_country  \
0     2026-02   HDS          AMER          Canada
1     2026-02   HDS          AMER          Canada
2     2026-02   HDS          AMER          Canada
3     2026-02   HDS          AMER          Canada
4     2026-02   HDS          AMER          Canada
...       ...   ...           ...             ...
1550  2026-03    HV          EMEA  United Kingdom
1551  2026-03    HV          EMEA  United Kingdom
1552  2026-03    HV          EMEA  United Kingdom
1553  2026-03    HV          EMEA  United Kingdom
1554  2026-03    HV          EMEA  United Kingdom

                                     entity_name account_name  \
0     Hitachi Digital Services Canada Inc. 00190   4000011853
1     Hitachi Digital Services Canada Inc. 00190   4000011853
2     Hitachi Digital Services Canada Inc. 00190   4000011853
3     Hitachi Digital Services Canada Inc. 00190   4000011853
4     Hitachi Digital Services Canada Inc. 00190   4000011853
...                                          ...          ...
1550   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439433
1551   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439441
1552   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439441
1553   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468
1554   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468

                level2                                             level5  \
0      Financing Flows  Increase (Decrease) - Loans from 3rd Party Len...
1       Free Cash Flow                                  A/R - Collections
2       Free Cash Flow                                 AP - OPEX Payments
3       Free Cash Flow        Adjustment to Reconcile Bank Activity to GL
4       Free Cash Flow                        Miscellaneous Disbursements
...                ...                                                ...
1550  Interco Receipts                            Interco Receipts - Loan
1551    Free Cash Flow                                  A/R - Collections
1552  Interco Payments                            Interco Payments - Loan
1553    Free Cash Flow                             Miscellaneous Receipts
1554  Interco Payments                            Interco Payments - Loan

      actual_amount
0              0.00
1        520,422.21
2       -168,396.23
3              0.00
4              0.00
...             ...
1550      29,630.51
1551      99,549.52
1552     -99,549.52
1553      14,952.69
1554     -14,952.69

[1555 rows x 9 columns]

In [9]:
df_actual_monthly.duplicated().sum()

0

In [10]:
# Cell 2: Load Data
data_path_2 = r'D:\PivotX_advisors\level5\Grid (Forecast Worksheet)_20260330_112016.csv'
df_actual_2 = pd.read_csv(data_path_2)

print(f"Dataset Shape: {df_actual_2.shape[0]:,} rows × {df_actual_2.shape[1]} columns")
# print(f"Date Range: {df_actual['date'].min()} to {df_actual['date'].max()}")
print(f"\nColumns: {df_actual_2.columns.tolist()}")
print(f"\nData Types:\n{df_actual_2.dtypes}")
# df_actual.head()

Dataset Shape: 1,208 rows × 17 columns

Columns: ['Account Name', 'Level 2', 'Level 5', 'Type', 'Mar 2026', 'Apr 2026', 'May 2026', 'Jun 2026', 'Jul 2026', 'Aug 2026', 'Sep 2026', 'Oct 2026', 'Nov 2026', 'Dec 2026', 'Jan 2027', 'Feb 2027', 'Mar 2027']

Data Types:
Account Name     object
Level 2          object
Level 5          object
Type             object
Mar 2026        float64
Apr 2026        float64
May 2026        float64
Jun 2026        float64
Jul 2026        float64
Aug 2026        float64
Sep 2026        float64
Oct 2026        float64
Nov 2026        float64
Dec 2026        float64
Jan 2027        float64
Feb 2027        float64
Mar 2027        float64
dtype: object

In [11]:
import pandas as pd

# 1. Identify which columns are dates and which are descriptive
# We want to keep Account Name, Level 2, Level 5, AND Type as static columns
id_cols = ['Account Name', 'Level 2', 'Level 5', 'Type']

# 2. Melt the dataframe
# This tells Pandas: "Keep these 4 columns as they are, and turn everything else into rows"
df_long = df_actual_2.melt(
    id_vars=id_cols, 
    var_name='Month', 
    value_name='Amount'
)

# 3. Clean up the 'Month' column
# Sometimes 'melt' catches extra header junk; we remove anything that isn't a date string
# We only keep rows where 'Month' actually looks like a date (e.g., contains '202')
df_long = df_long[df_long['Month'].str.contains('202', na=False)]

# 4. Apply your Level filters
df_clean = df_long.dropna(subset=['Level 2', 'Level 5']).copy()

# 5. Now convert to datetime (this should work without errors now)
df_clean['Month'] = pd.to_datetime(df_clean['Month'], format='%b %Y')

# 6. Final Sort
df_clean = df_clean.sort_values(['Account Name', 'Month'])

print(df_clean.head())

         Account Name         Level 2                      Level 5     Type  \
2     0-051-0045665-8  Free Cash Flow  Miscellaneous Disbursements  Netflow
1210  0-051-0045665-8  Free Cash Flow  Miscellaneous Disbursements  Netflow
2418  0-051-0045665-8  Free Cash Flow  Miscellaneous Disbursements  Netflow
3626  0-051-0045665-8  Free Cash Flow  Miscellaneous Disbursements  Netflow
4834  0-051-0045665-8  Free Cash Flow  Miscellaneous Disbursements  Netflow

          Month     Amount
2    2026-03-01 -13,305.00
1210 2026-04-01       0.00
2418 2026-05-01       0.00
3626 2026-06-01       0.00
4834 2026-07-01       0.00

In [12]:
df_clean['Month'] = pd.to_datetime(df_clean['Month'], format='%b %Y', errors='coerce')
df_clean = df_clean.dropna(subset=['Month'])

In [13]:
# Filter out rows where the month is March (3)
df_clean = df_clean[df_clean['Month'].dt.month != 3]

# Verify the result
print(df_clean['Month'].unique())

<DatetimeArray>
['2026-04-01 00:00:00', '2026-05-01 00:00:00', '2026-06-01 00:00:00',
 '2026-07-01 00:00:00', '2026-08-01 00:00:00', '2026-09-01 00:00:00',
 '2026-10-01 00:00:00', '2026-11-01 00:00:00', '2026-12-01 00:00:00',
 '2027-01-01 00:00:00', '2027-02-01 00:00:00']
Length: 11, dtype: datetime64[ns]

In [14]:
# Rename columns
df_clean = df_clean.rename(columns={
        # "Region": "entity_region",
        # "Country": "entity_country",
    "Account Name": "account_name",
    "Level 2": "level2",
    "Level 5": "level5",
    "Amount": "actual_amount"
})

# Step 1: Drop old region
# df_long = df_long.drop(columns=["entity_country"])
df_clean=df_clean.dropna()
# Step 2: Create mapping table (unique values only)
mapping_cols = ["account_name",  "opcos", 'entity_region','entity_country','entity_name']

df_map = df_actual_1[mapping_cols].drop_duplicates()

# Step 3: Merge (LEFT JOIN)
df_clean = df_clean.merge(
    df_map,
    on=["account_name"],   # adjust if needed
    how="left"
)
# df_clean['level2'] = df_clean['level5'].map(level2_map)
# Step 4: Reorder columns (optional)
df_clean = df_clean[
    ["Month", "opcos", "entity_region",'entity_country','entity_name','account_name','level2', 'level5',"actual_amount"]
]
df_clean.head()

,Month,opcos,entity_region,entity_country,entity_name,account_name,level2,level5,actual_amount
0,2026-04-01,HV,AMER,Chile,HITACHI VANTARA (CHILE) LIMITADA 330,0-051-0045665-8,Free Cash Flow,Miscellaneous Disbursements,0.00
1,2026-05-01,HV,AMER,Chile,HITACHI VANTARA (CHILE) LIMITADA 330,0-051-0045665-8,Free Cash Flow,Miscellaneous Disbursements,0.00
2,2026-06-01,HV,AMER,Chile,HITACHI VANTARA (CHILE) LIMITADA 330,0-051-0045665-8,Free Cash Flow,Miscellaneous Disbursements,0.00
3,2026-07-01,HV,AMER,Chile,HITACHI VANTARA (CHILE) LIMITADA 330,0-051-0045665-8,Free Cash Flow,Miscellaneous Disbursements,0.00
4,2026-08-01,HV,AMER,Chile,HITACHI VANTARA (CHILE) LIMITADA 330,0-051-0045665-8,Free Cash Flow,Miscellaneous Disbursements,0.00

In [15]:
import pandas as pd

# Ensure date column is datetime
# df_clean['date'] = pd.to_datetime(df_clean['date'], errors='coerce')
# Add level2 mapping
# df_forecast['level2'] = df_forecast['level5'].map(level2_map)

# Create year-month period column
df_clean['month'] = df_clean['Month'].dt.to_period('M')

# Group by monthly level
df_actual_monthly_2 = (
    df_clean.groupby(['month', 'opcos', 'entity_region','entity_country','entity_name','account_name','level2','level5'], as_index=False)
    ['actual_amount']
    .sum()
)

print(df_actual_monthly_2)

        month opcos entity_region  entity_country  \
0     2026-04   HDS          AMER          Canada
1     2026-04   HDS          AMER          Canada
2     2026-04   HDS          AMER          Canada
3     2026-04   HDS          AMER          Canada
4     2026-04   HDS          AMER          Canada
...       ...   ...           ...             ...
7827  2027-02    HV          EMEA  United Kingdom
7828  2027-02    HV          EMEA  United Kingdom
7829  2027-02    HV          EMEA  United Kingdom
7830  2027-02    HV          EMEA  United Kingdom
7831  2027-02    HV          EMEA  United Kingdom

                                     entity_name account_name  \
0     Hitachi Digital Services Canada Inc. 00190   4000011853
1     Hitachi Digital Services Canada Inc. 00190   4000011853
2     Hitachi Digital Services Canada Inc. 00190   4000011853
3     Hitachi Digital Services Canada Inc. 00190   4000011853
4     Hitachi Digital Services Canada Inc. 00190   4000011853
...                                          ...          ...
7827   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468
7828   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468
7829   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
7830   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
7831   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145

                level2                                             level5  \
0      Financing Flows  Increase (Decrease) - Loans from 3rd Party Len...
1       Free Cash Flow                                  A/R - Collections
2       Free Cash Flow                                 AP - OPEX Payments
3       Free Cash Flow        Adjustment to Reconcile Bank Activity to GL
4       Free Cash Flow                        Miscellaneous Disbursements
...                ...                                                ...
7827    Free Cash Flow                             Miscellaneous Receipts
7828  Interco Payments                            Interco Payments - Loan
7829    Free Cash Flow                                  A/R - Collections
7830    Free Cash Flow                         Related Parties - Receipts
7831  Interco Payments                            Interco Payments - Loan

      actual_amount
0              0.00
1        740,348.81
2        -21,921.81
3              0.00
4              0.00
...             ...
7827           0.00
7828           0.00
7829           0.00
7830           0.00
7831           0.00

[7832 rows x 9 columns]

In [16]:
df_actual_monthly_2.duplicated().sum()

0

In [17]:
df_actual_monthly=pd.concat([df_actual_monthly, df_actual_monthly_2], axis=0)
print(df_actual_monthly)

        month opcos entity_region  entity_country  \
0     2026-02   HDS          AMER          Canada
1     2026-02   HDS          AMER          Canada
2     2026-02   HDS          AMER          Canada
3     2026-02   HDS          AMER          Canada
4     2026-02   HDS          AMER          Canada
...       ...   ...           ...             ...
7827  2027-02    HV          EMEA  United Kingdom
7828  2027-02    HV          EMEA  United Kingdom
7829  2027-02    HV          EMEA  United Kingdom
7830  2027-02    HV          EMEA  United Kingdom
7831  2027-02    HV          EMEA  United Kingdom

                                     entity_name account_name  \
0     Hitachi Digital Services Canada Inc. 00190   4000011853
1     Hitachi Digital Services Canada Inc. 00190   4000011853
2     Hitachi Digital Services Canada Inc. 00190   4000011853
3     Hitachi Digital Services Canada Inc. 00190   4000011853
4     Hitachi Digital Services Canada Inc. 00190   4000011853
...                                          ...          ...
7827   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468
7828   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288     12439468
7829   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
7830   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145
7831   HITACHI VANTARA NEDERLAND B.V. (MEMA) 288   2032287145

                level2                                             level5  \
0      Financing Flows  Increase (Decrease) - Loans from 3rd Party Len...
1       Free Cash Flow                                  A/R - Collections
2       Free Cash Flow                                 AP - OPEX Payments
3       Free Cash Flow        Adjustment to Reconcile Bank Activity to GL
4       Free Cash Flow                        Miscellaneous Disbursements
...                ...                                                ...
7827    Free Cash Flow                             Miscellaneous Receipts
7828  Interco Payments                            Interco Payments - Loan
7829    Free Cash Flow                                  A/R - Collections
7830    Free Cash Flow                         Related Parties - Receipts
7831  Interco Payments                            Interco Payments - Loan

      actual_amount
0              0.00
1        520,422.21
2       -168,396.23
3              0.00
4              0.00
...             ...
7827           0.00
7828           0.00
7829           0.00
7830           0.00
7831           0.00

[9387 rows x 9 columns]

In [18]:
df_actual_monthly.duplicated().sum()
# print(df_actual_monthly)

0

In [19]:
print(len(df_actual_monthly))
print(len(df_forecast_monthly))

9387
2862

In [18]:
df_new = df_actual_monthly.merge(
    df_forecast_monthly[['month', 'opcos', 'entity_region','entity_country','entity_name','account_name','level2','level5','forecast_amount','forecast_amount_uncapped']],
    on=['month', 'opcos', 'entity_region','entity_country','entity_name','account_name','level2','level5'],
    how='outer'   # keeps all rows from both dataframes 
)

df_new[:100]

,month,opcos,entity_region,entity_country,entity_name,account_name,level2,level5,actual_amount,forecast_amount,forecast_amount_uncapped
0,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,0.00,NaN,NaN
1,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,A/R - Collections,"520,422.21","234,141.99","709,521.19"
2,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,AP - OPEX Payments,"-168,396.23","-96,183.30","-291,464.54"
3,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN
4,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Miscellaneous Disbursements,0.00,NaN,NaN
5,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Miscellaneous Receipts,0.00,NaN,NaN
6,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Payroll Payments,"-278,337.40","-120,661.33","-365,640.39"
7,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Product Payments - Hitachi Ltd Group,0.00,NaN,NaN
8,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Related Parties - Payments,0.00,NaN,NaN
9,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Related Parties - Receipts,0.00,0.00,0.00
10,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Tax Payments,0.00,NaN,NaN
11,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Payments,Interco Payments - Dividends,0.00,NaN,NaN
12,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Payments,Interco Payments - Loan,0.00,NaN,NaN
13,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Payments,Interco Payments - Trade,0.00,NaN,NaN
14,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Receipts,Interco Receipts - Dividends,0.00,NaN,NaN
15,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Receipts,Interco Receipts - Loan,0.00,NaN,NaN
16,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Interco Receipts,Interco Receipts - Trade,0.00,NaN,NaN
17,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,0.00,NaN,NaN
18,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,A/R - Collections,"160,314.07","1,106,133.91","368,711.30"
19,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,AP - OPEX Payments,-300.40,"-1,159,623.84","-386,541.28"
20,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN
21,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Miscellaneous Disbursements,0.00,NaN,NaN
22,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Miscellaneous Receipts,0.00,NaN,NaN
23,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Payroll Payments,0.00,NaN,NaN
24,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Product Payments - Hitachi Ltd Group,0.00,NaN,NaN
25,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Related Parties - Payments,0.00,NaN,NaN
26,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Related Parties - Receipts,0.00,NaN,NaN
27,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Free Cash Flow,Tax Payments,0.00,NaN,NaN
28,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Payments,Interco Payments - Dividends,0.00,NaN,NaN
29,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Payments,Interco Payments - Loan,0.00,NaN,NaN
30,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Payments,Interco Payments - Trade,0.00,NaN,NaN
31,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Receipts,Interco Receipts - Dividends,0.00,NaN,NaN
32,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Receipts,Interco Receipts - Loan,0.00,NaN,NaN
33,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011855,Interco Receipts,Interco Receipts - Trade,0.00,NaN,NaN
34,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,566538867,Free Cash Flow,AP - OPEX Payments,NaN,0.00,0.00
35,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,566538867,Free Cash Flow,Payroll Payments,NaN,0.00,0.00
36,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,566538867,Interco Receipts,Interco Receipts - Trade,NaN,0.00,0.00
37,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,A/R - Collections,NaN,0.00,0.00
38,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,AP - OPEX Payments,NaN,"-11,676.71","-35,383.96"
39,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,Miscellaneous Receipts,NaN,231.11,700.34
40,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,Payroll Payments,NaN,"-42,500.10","-128,788.19"
41,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,Related Parties - Receipts,NaN,407.06,"1,233.53"
42,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Free Cash Flow,Tax Payments,NaN,0.00,0.00
43,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Interco Payments,Interco Payments - Trade,NaN,0.00,0.00
44,2026-02,HDS,AMER,US,Hitachi Digital Services Asia Pacific Inc. 00193,604430082,Interco Receipts,Interco Receipts - Trade,NaN,"554,399.90","184,799.97"
45,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,"-5,435,956.83","567,267.68","1,718,992.96"
46,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,A/R - Collections,"25,499,923.62","34,160,314.60","43,949,155.70"
47,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,AP - OPEX Payments,"-6,242,251.68","-13,887,490.92","-17,867,033.95"
48,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN
49,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Miscellaneous Disbursements,0.00,NaN,NaN
50,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Miscellaneous Receipts,0.00,0.00,0.00
51,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Payroll Payments,"-6,510,578.65","-8,586,352.02","-11,046,822.20"
52,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Product Payments - Hitachi Ltd Group,0.00,NaN,NaN
53,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Related Parties - Payments,"-3,260,631.87","-2,681,723.20","-3,450,186.91"
54,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Related Parties - Receipts,"4,320,623.35","925,919.71","1,191,247.50"
55,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Free Cash Flow,Tax Payments,0.00,NaN,NaN
56,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Payments,Interco Payments - Dividends,0.00,NaN,NaN
57,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Payments,Interco Payments - Loan,0.00,NaN,NaN
58,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Payments,Interco Payments - Trade,"-10,107,578.36","-8,126,767.67","-9,947,912.83"
59,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Receipts,Interco Receipts - Dividends,0.00,NaN,NaN
60,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Receipts,Interco Receipts - Loan,"688,703.10",NaN,NaN
61,2026-02,HDS,AMER,US,Hitachi Digital Services LLC 00101,1597754520,Interco Receipts,Interco Receipts - Trade,0.00,0.00,0.00
62,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,"-2,721,355.00","-4,788,542.76","-4,788,542.76"
63,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,A/R - Collections,"2,050,665.03","1,446,154.32","1,569,870.60"
64,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,AP - OPEX Payments,"-1,771,019.34","-1,395,417.39","-1,514,793.20"
65,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN
66,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Miscellaneous Disbursements,"-2,285,938.20","-2,141,729.13","-2,324,950.76"
67,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Miscellaneous Receipts,"336,059.72","314,808.14","341,739.49"
68,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Payroll Payments,"-5,356,605.19","-5,662,955.12","-6,147,412.23"
69,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Product Payments - Hitachi Ltd Group,0.00,NaN,NaN
70,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Related Parties - Payments,0.00,NaN,NaN
71,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Related Parties - Receipts,"917,821.88","843,735.39","915,915.66"
72,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Free Cash Flow,Tax Payments,"-879,246.48","-2,577,384.45","-2,797,875.73"
73,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Payments,Interco Payments - Dividends,0.00,NaN,NaN
74,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Payments,Interco Payments - Loan,0.00,NaN,NaN
75,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Payments,Interco Payments - Trade,0.00,NaN,NaN
76,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Receipts,Interco Receipts - Dividends,0.00,0.00,0.00
77,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Receipts,Interco Receipts - Loan,0.00,NaN,NaN
78,2026-02,HDS,APAC,India,Hitachi Digital Services India Private Limited...,5622418068,Interco Receipts,Interco Receipts - Trade,"7,987,001.63","10,036,067.65","5,953,389.11"
79,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,0.00,NaN,NaN
80,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,A/R - Collections,"1,091,618.38","1,710,421.22","1,614,170.16"
81,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,AP - OPEX Payments,"-95,423.01","-81,032.10","-76,472.16"
82,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN
83,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Miscellaneous Disbursements,0.00,NaN,NaN
84,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Miscellaneous Receipts,474.28,172.71,162.99
85,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Payroll Payments,"-93,221.13","-79,718.31","-75,232.30"
86,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Product Payments - Hitachi Ltd Group,0.00,NaN,NaN
87,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Related Parties - Payments,0.00,NaN,NaN
88,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Related Parties - Receipts,"10,131.04","5,240.74","4,945.83"
89,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Free Cash Flow,Tax Payments,"-76,341.98","-142,540.97","-134,519.72"
90,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Payments,Interco Payments - Dividends,0.00,NaN,NaN
91,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Payments,Interco Payments - Loan,0.00,NaN,NaN
92,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Payments,Interco Payments - Trade,"-1,357,722.11","-1,401,034.35","-1,401,034.35"
93,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Receipts,Interco Receipts - Dividends,0.00,NaN,NaN
94,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Receipts,Interco Receipts - Loan,0.00,NaN,NaN
95,2026-02,HDS,APAC,Japan,"Hitachi Digital Services Japan, K.K. 00475",0152554689,Interco Receipts,Interco Receipts - Trade,"16,576.80","1,474.10","1,474.10"
96,2026-02,HDS,APAC,Singapore,Hitachi Digital Services APAC Holding Pte Ltd ...,047844360001,Free Cash Flow,AP - OPEX Payments,NaN,0.00,0.00
97,2026-02,HDS,APAC,Singapore,Hitachi Digital Services APAC Holding Pte Ltd ...,047844360001,Free Cash Flow,Miscellaneous Disbursements,NaN,0.00,0.00
98,2026-02,HDS,APAC,Singapore,Hitachi Digital Services APAC Holding Pte Ltd ...,047844360001,Free Cash Flow,Miscellaneous Receipts,NaN,0.00,0.00
99,2026-02,HDS,APAC,Singapore,Hitachi Digital Services APAC Holding Pte Ltd ...,260815139178,Free Cash Flow,AP - OPEX Payments,NaN,0.00,0.00

In [20]:
df_grouped = df_new.groupby(
    ['month', 'opcos', 'entity_region', 'level2']
).agg({
    'actual_amount': 'sum' ,
    'forecast_amount': 'sum',
    'forecast_amount_uncapped': 'sum'
      # if exists
}).reset_index()

df_grouped[:100]

,month,opcos,entity_region,level2,actual_amount,forecast_amount,forecast_amount_uncapped
0,2026-02,HDS,AMER,Financing Flows,"-5,435,956.83","567,267.68","1,718,992.96"
1,2026-02,HDS,AMER,Free Cash Flow,"14,040,787.02","9,840,936.97","12,648,708.13"
2,2026-02,HDS,AMER,Interco Payments,"-10,107,578.36","-8,126,767.67","-9,947,912.83"
3,2026-02,HDS,AMER,Interco Receipts,"688,703.10","554,399.90","184,799.97"
4,2026-02,HDS,APAC,Financing Flows,"-2,721,355.00","-4,788,542.76","-4,788,542.76"
5,2026-02,HDS,APAC,Free Cash Flow,"-5,043,468.84","-9,165,303.02","-10,889,643.35"
6,2026-02,HDS,APAC,Interco Payments,"-3,515,636.44","-955,350.96","-955,350.96"
7,2026-02,HDS,APAC,Interco Receipts,"10,254,816.60","11,723,648.38","7,554,746.23"
8,2026-02,HDS,EMEA,Financing Flows,-0.00,0.00,0.00
9,2026-02,HDS,EMEA,Free Cash Flow,"2,848,167.17","1,563,516.59","2,793,783.35"
10,2026-02,HDS,EMEA,Interco Payments,"-928,670.36","-4,146,744.61","-2,119,538.41"
11,2026-02,HDS,EMEA,Interco Receipts,"928,670.36","732,160.81","671,478.71"
12,2026-02,HV,AMER,Financing Flows,"16,090,501.17","-25,581,006.55","-18,771,519.16"
13,2026-02,HV,AMER,Free Cash Flow,"-54,282,008.05","-204,048,513.25","-119,176,856.01"
14,2026-02,HV,AMER,Interco Payments,"-3,243,065.42","-43,380,967.40","-48,735,284.74"
15,2026-02,HV,AMER,Interco Receipts,"43,651,836.70","38,692,708.62","59,415,715.65"
16,2026-02,HV,AMER,Investments,0.00,0.00,0.00
17,2026-02,HV,APAC,Free Cash Flow,"24,930,537.85","31,515,960.41","32,146,460.36"
18,2026-02,HV,APAC,Interco Payments,"-36,654,704.71","-43,287,999.71","-28,116,607.78"
19,2026-02,HV,APAC,Interco Receipts,"2,007,570.48","11,932,006.78","12,355,197.30"
20,2026-02,HV,EMEA,Free Cash Flow,"29,289,412.89","17,103,467.52","15,004,161.30"
21,2026-02,HV,EMEA,Interco Payments,"-391,062,721.71","-391,986,706.20","-400,732,647.49"
22,2026-02,HV,EMEA,Interco Receipts,"394,440,466.80","306,086,953.03","370,434,452.56"
23,2026-03,HDS,AMER,Financing Flows,0.00,0.00,0.00
24,2026-03,HDS,AMER,Free Cash Flow,0.00,"6,445,350.51","9,281,244.50"
25,2026-03,HDS,AMER,Interco Payments,0.00,"-7,338,558.84","-9,947,912.83"
26,2026-03,HDS,AMER,Interco Receipts,0.00,"300,760.66","100,253.55"
27,2026-03,HDS,APAC,Financing Flows,0.00,"-4,426,936.93","-4,426,936.93"
28,2026-03,HDS,APAC,Free Cash Flow,0.00,"-7,451,845.09","-7,551,205.51"
29,2026-03,HDS,APAC,Interco Payments,0.00,"-1,415,443.66","-1,415,443.66"
30,2026-03,HDS,APAC,Interco Receipts,0.00,"15,371,513.35","13,671,442.77"
31,2026-03,HDS,EMEA,Free Cash Flow,0.00,"1,717,059.68","2,040,118.74"
32,2026-03,HDS,EMEA,Interco Payments,0.00,"-4,146,744.61","-2,119,538.41"
33,2026-03,HDS,EMEA,Interco Receipts,0.00,"732,160.81","671,478.71"
34,2026-03,HV,AMER,Financing Flows,0.00,"33,533,490.58","42,662,478.34"
35,2026-03,HV,AMER,Free Cash Flow,0.00,"-140,754,400.23","-144,093,576.73"
36,2026-03,HV,AMER,Interco Payments,0.00,"-18,348,631.35","-11,960,549.53"
37,2026-03,HV,AMER,Interco Receipts,0.00,"55,990,759.73","49,424,562.41"
38,2026-03,HV,APAC,Free Cash Flow,"1,739,711.12","33,839,030.27","31,401,602.61"
39,2026-03,HV,APAC,Interco Payments,"-18,564,215.34","-29,641,000.76","-37,644,599.22"
40,2026-03,HV,APAC,Interco Receipts,0.00,"5,568,415.71","4,857,162.67"
41,2026-03,HV,EMEA,Free Cash Flow,"8,932,333.63","23,587,262.43","1,333,109.88"
42,2026-03,HV,EMEA,Interco Payments,"-62,732,290.23","-343,893,374.48","-322,524,507.73"
43,2026-03,HV,EMEA,Interco Receipts,"62,724,283.97","348,999,447.33","406,273,126.83"
44,2026-04,HDS,AMER,Financing Flows,0.00,0.00,0.00
45,2026-04,HDS,AMER,Free Cash Flow,"13,791,887.75","4,396,173.88","8,731,148.69"
46,2026-04,HDS,AMER,Interco Payments,"-9,600,000.00","-11,560,865.76","-14,601,070.42"
47,2026-04,HDS,AMER,Interco Receipts,"4,200,152.46","1,536,150.58","1,179,185.51"
48,2026-04,HDS,APAC,Financing Flows,0.00,"-11,230,930.72","-11,230,930.72"
49,2026-04,HDS,APAC,Free Cash Flow,"6,449,938.90","-7,779,582.42","-10,316,692.21"
50,2026-04,HDS,APAC,Interco Payments,"-3,000,152.42","-1,620,252.51","-1,620,252.51"
51,2026-04,HDS,APAC,Interco Receipts,"9,600,000.00","12,246,604.96","7,264,260.39"
52,2026-04,HDS,EMEA,Financing Flows,0.00,0.00,0.00
53,2026-04,HDS,EMEA,Free Cash Flow,"-387,871.48","1,944,327.49","3,621,640.76"
54,2026-04,HDS,EMEA,Interco Payments,"-3,290,131.57","-3,049,671.69","-2,119,538.41"
55,2026-04,HDS,EMEA,Interco Receipts,"2,090,131.53","1,458,914.80","1,427,959.25"
56,2026-04,HV,AMER,Financing Flows,0.00,"-25,581,006.55","-22,813,502.17"
57,2026-04,HV,AMER,Free Cash Flow,0.00,"-119,618,813.06","-137,071,686.64"
58,2026-04,HV,AMER,Interco Payments,"-2,196,956.00","-24,717,087.76","-22,600,093.73"
59,2026-04,HV,AMER,Interco Receipts,"28,733,863.81","66,276,285.50","79,209,812.19"
60,2026-04,HV,AMER,Investments,0.00,0.00,0.00
61,2026-04,HV,APAC,Free Cash Flow,"7,058,020.13","28,081,307.98","32,889,220.33"
62,2026-04,HV,APAC,Interco Payments,"-28,733,863.81","-36,239,532.12","-22,389,089.90"
63,2026-04,HV,APAC,Interco Receipts,"2,196,956.00","8,515,914.41","9,147,696.35"
64,2026-04,HV,EMEA,Free Cash Flow,"-40,151,080.70","31,499,379.93","23,736,289.47"
65,2026-04,HV,EMEA,Interco Payments,"-228,724,923.60","-325,260,736.91","-346,927,025.30"
66,2026-04,HV,EMEA,Interco Receipts,"228,724,923.46","293,098,768.00","337,444,870.80"
67,2026-05,HDS,AMER,Financing Flows,0.00,0.00,0.00
68,2026-05,HDS,AMER,Free Cash Flow,"15,267,629.30",0.00,0.00
69,2026-05,HDS,AMER,Interco Payments,"-9,600,000.00",0.00,0.00
70,2026-05,HDS,AMER,Interco Receipts,"2,700,076.25",0.00,0.00
71,2026-05,HDS,APAC,Financing Flows,0.00,0.00,0.00
72,2026-05,HDS,APAC,Free Cash Flow,"-4,168,183.78",0.00,0.00
73,2026-05,HDS,APAC,Interco Payments,"-1,500,076.21",0.00,0.00
74,2026-05,HDS,APAC,Interco Receipts,"9,600,000.00",0.00,0.00
75,2026-05,HDS,EMEA,Financing Flows,0.00,0.00,0.00
76,2026-05,HDS,EMEA,Free Cash Flow,"-541,408.78",0.00,0.00
77,2026-05,HDS,EMEA,Interco Payments,"-2,759,471.19",0.00,0.00
78,2026-05,HDS,EMEA,Interco Receipts,"1,559,471.15",0.00,0.00
79,2026-05,HV,AMER,Financing Flows,0.00,0.00,0.00
80,2026-05,HV,AMER,Free Cash Flow,0.00,0.00,0.00
81,2026-05,HV,AMER,Interco Payments,"-2,196,956.00",0.00,0.00
82,2026-05,HV,AMER,Interco Receipts,"23,733,863.81",0.00,0.00
83,2026-05,HV,AMER,Investments,0.00,0.00,0.00
84,2026-05,HV,APAC,Free Cash Flow,"20,568,652.47",0.00,0.00
85,2026-05,HV,APAC,Interco Payments,"-23,733,863.81",0.00,0.00
86,2026-05,HV,APAC,Interco Receipts,"2,196,956.00",0.00,0.00
87,2026-05,HV,EMEA,Free Cash Flow,"-21,264,659.20",0.00,0.00
88,2026-05,HV,EMEA,Interco Payments,"-154,981,977.96",0.00,0.00
89,2026-05,HV,EMEA,Interco Receipts,"154,981,977.80",0.00,0.00
90,2026-06,HDS,AMER,Financing Flows,0.00,0.00,0.00
91,2026-06,HDS,AMER,Free Cash Flow,"15,267,629.34",0.00,0.00
92,2026-06,HDS,AMER,Interco Payments,"-9,600,000.00",0.00,0.00
93,2026-06,HDS,AMER,Interco Receipts,"2,700,076.25",0.00,0.00
94,2026-06,HDS,APAC,Financing Flows,0.00,0.00,0.00
95,2026-06,HDS,APAC,Free Cash Flow,"-10,540,094.11",0.00,0.00
96,2026-06,HDS,APAC,Interco Payments,"-1,500,076.21",0.00,0.00
97,2026-06,HDS,APAC,Interco Receipts,"9,600,000.00",0.00,0.00
98,2026-06,HDS,EMEA,Financing Flows,0.01,0.00,0.00
99,2026-06,HDS,EMEA,Free Cash Flow,"827,466.68",0.00,0.00

In [21]:
import numpy as np

# add abs_variance1 column after actual_amount
df_new.insert(
    df_new.columns.get_loc('forecast_amount_uncapped') + 1,
    'abs_variance',
    (df_new['actual_amount'] - df_new['forecast_amount']).abs()
)

# denominator = max(|actual|, |forecast|)
denominator = np.maximum(
    df_new['actual_amount'].abs(),
    df_new['forecast_amount'].abs()
)

# pct change
pct_change = (df_new['abs_variance'] / df_new['actual_amount'] ) * 100

# sign rule
sign = np.where(df_new['forecast_amount'] * df_new['actual_amount'] < 0, -1, 1)

df_new.insert(
    loc=df_new.columns.get_loc('abs_variance') + 1,
    column='pct_change',
    value=pct_change
)

df_new.head(1)

# Create accuracy first
accuracy = 100 - df_new['pct_change'].abs()

# Keep within 0–100
accuracy = accuracy.clip(0, 100)

# Insert right after pct_change
df_new.insert(
    loc=df_new.columns.get_loc('pct_change') + 1,
    column='accuracy',
    value=accuracy
)
df_new.head()

,month,opcos,entity_region,entity_country,entity_name,account_name,level2,level5,actual_amount,forecast_amount,forecast_amount_uncapped,abs_variance,pct_change,accuracy
0,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Financing Flows,Increase (Decrease) - Loans from 3rd Party Len...,0.00,NaN,NaN,NaN,NaN,NaN
1,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,A/R - Collections,"520,422.21","234,141.99","709,521.19","286,280.22",55.01,44.99
2,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,AP - OPEX Payments,"-168,396.23","-96,183.30","-291,464.54","72,212.93",-42.88,57.12
3,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Adjustment to Reconcile Bank Activity to GL,0.00,NaN,NaN,NaN,NaN,NaN
4,2026-02,HDS,AMER,Canada,Hitachi Digital Services Canada Inc. 00190,4000011853,Free Cash Flow,Miscellaneous Disbursements,0.00,NaN,NaN,NaN,NaN,NaN

In [22]:
df_new.drop_duplicates(inplace=True)

In [23]:
df_new.to_csv(r'D:\PivotX_advisors\Abhishek_csvs\comparison_level5_new_recon.csv', index=False)

In [24]:
df_grouped.to_csv(r'D:\PivotX_advisors\Abhishek_csvs\comparison_level2_new_recon.csv', index=False)

In [25]:
#calculate wmape for forecast_amount
wmape = df_new['abs_variance'].sum() / df_new['actual_amount'].abs().sum() * 100
print(f"WMAPE for forecast_amount: {wmape:.2f}%")

WMAPE for forecast_amount: 74.22%